#%RAML 1.0
title: Plant State API
mediaType:
  - application/json
version: 1.0.0
protocols:
  - HTTPS
/events:
  post:
    displayName: Post Events
    description: Post event details.
    responses:
      "200":
        body:
          application/json:
            example:
              strict: true
              value:
                result: Event created successfully.
            type: object
    body:
      application/json:
        example:
          strict: true
          value:
            event:
              eventTypeId: 1
              plantId: 2
        type: object




